// Global app state
const state = {
      currentUser: null,
      currentGroup: null,
      currentMembership: null,
      currentProfile: null,
      isAuthBootstrapping: true,
      isAuthActionPending: false,
      hasResolvedMembership: false,
      groupMode: 'create',
      members: [],
      availabilityBlocks: [],
      openScheduleSections: {},
      currentView: 'dashboard',
      messages: [],
      tasks: [],
      resources: [],
      alerts: [],
      editingTaskId: null,
      contributions: [],
      realtimeChannels: [],
      realtimeGroupId: null,
      memberIndexByDbId: new Map(),
      memberByDbId: new Map(),
      isHydratingInitialData: false,
      pendingRealtimeTables: new Set(),
      hasRenderedSchedule: false,
      // MVP E2EE caches
      groupContentKeys: {},
      userKeypairReady: false,
      userKeypair: null,
    };
