// Global app state
const state = {
      currentUser: null,
      currentGroup: null,
      currentMembership: null,
      currentProfile: null,
      isAuthBootstrapping: true,
      isAuthActionPending: false,
      hasResolvedMembership: false,
      groupMode: 'create',
      members: [],
      availabilityBlocks: [],
      openScheduleSections: {},
      currentView: 'dashboard',
      messages: [],
      tasks: [],
      resources: [],
      alerts: [],
      editingTaskId: null,
      contributions: [],
      realtimeChannels: [],
      realtimeGroupId: null,
      realtimePendingGroupId: null,
      realtimeRetryTimer: null,
      realtimeRetryCount: 0,
      realtimeAttemptSeq: 0,
      messagesRealtime: {
        groupId: null,
        channel: null,
        attemptId: 0,
        status: 'idle'
      },
      memberIndexByDbId: new Map(),
      memberByDbId: new Map(),
      isHydratingInitialData: false,
      pendingRealtimeTables: new Set(),
      hasRenderedSchedule: false,
      // MVP E2EE caches
      groupContentKeys: {},
      groupEnvelopeBackfillInFlight: {},
      groupEnvelopeBackfillLastRunAt: {},
      userKeypairReady: false,
      userKeypair: null,
      e2eeInitWarning: '',
    };
